### PR TITLE
Logging tweak - turn down the noise in dev

### PR DESCRIPTION
**Pull request by rsanheim**
This turns down the constant noise from resque workers polling.  This will only log the "Sleeping for xx seconds" messages if `VERBOSE` or `VVERBOSE` are true.

/cc @mgbatchelor @GilUpstream

### CODE REVIEW

**Comment by mgbatchelor** [comment]
Are we currently using a fork of Resque? 😢

**Comment by rsanheim** [comment]
> Are we currently using a fork of Resque? 😢

No, this is a new fork.  If you [look at the source](https://github.com/resque/resque/blob/a3680c7b4ef65cea7f2a568c842c7443acd8e385/lib/resque/worker.rb#L244-L245) that is constantly filling the log in dev, though, there is not really an easy way to override or monkey patch that piece and still maintain DEBUG logging in dev.

**Comment by rsanheim** [comment]
Hm, this is based against master, but should really be based against 1.26.0.  I'll fix that up.

**Comment by rick** [comment]
Oh, there's a way ... 😁 

I think it would be possible to monkey-patch `log_with_severity` and have it do the normal thing generally, but:

 - Maybe (less likely): only output debug stuff if `VERBOSE` or `VVERBOSE` is set.  This probably squelches too much debug output, but not sure
 - Same, but tighten the condition so that we check either the message being sent, or check where `caller()` says we're being called from; and only conditionalize in those cases.

**Comment by rsanheim** [comment]
> Oh, there's a way ...

heh. I realize there is always a way in Ruby.  Bug I think the monkeypatch + analyzing the message is worse than the approach here.

**Comment by ymendel** [comment]
Is this something we can/will submit as a patch to be possibly accepted so that we won't have to long-term deal with a fork simply because of these annoying-as-heck log messages?

As an aside, it's kind of amazing that Resque uses `VERBOSE` and `VVERBOSE` instead of, say, a verbosity level.

**Pull request closed without merging**
